interface wlan0
static ip_address=10.0.3.14/22
static routers=10.0.3.254
static domain_name_servers=10.0.3.254

interface eth0
static ip_address=10.0.100.8/24
static routers=10.0.100.1
static domain_name_servers=10.0.100.1
