network:
  version: 2
  ethernets:
    ### Bridge: 10.0.100.0/24 => main link
    enp2s0:
      addresses:
        - 10.0.100.210/24
      routes:
        - to: default
          via: 10.0.100.1
      nameservers:
        addresses:
          - 10.0.100.1
