interface wlan0
static ip_address=10.0.3.231/22
static routers=10.0.3.254
static domain_name_servers=10.0.3.254

interface eth0
static ip_address=11.11.11.11/24 ## そのネットワークで無効なアドレスを割り当てておくことでDHCPによるアドレス割り当てを回避する
static ip6_address=fde4:db8::a2/64

interface eth1
static ip_address=198.18.0.1/16
static ip6_address=2001:0db8:c0ff:ee00::1/64
