interface wlan0
static ip_address=10.0.3.10/22
static routers=10.0.3.254
static domain_name_servers=10.0.3.254

interface eth0
static ip_address=198.18.0.1/16
static ip6_address=2001:0db8:c0ff:ee00::1/64
