interface wlan0
static ip_address=10.0.3.12/22
static routers=10.0.3.254
static domain_name_servers=10.0.3.254

interface eth0
static ip_address=10.0.100.6/24
static routers=10.0.100.1
static domain_name_servers=10.0.100.1

interface eth0
static ip6_address=fde4:db8::102/8
